#! /usr/bin/env ruby

app_name = ARGV[0]

['addon-manifest.json', 'app.rb'].each do |fname|
  app_file = File.read(fname)
  app_file.gsub!(/myaddon/, app_name.downcase)
  app_file.gsub!(/MYADDON/, app_name.upcase)
  File.open(fname, 'w') { |f| f << app_file }
end

puts "Replaced all instances of MYADDON and myaddon with #{app_name}"
